CREATE TABLE IF NOT EXISTS result_easy (
  id BINARY(16) PRIMARY KEY,
  userId VARCHAR(24) NOT NULL,
  timeElapsed MEDIUMINT UNSIGNED NOT NULL,
  clicks SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS result_medium (
  id BINARY(16) PRIMARY KEY,
  userId VARCHAR(24) NOT NULL,
  timeElapsed MEDIUMINT UNSIGNED NOT NULL,
  clicks SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS result_hard (
  id BINARY(16) PRIMARY KEY,
  userId VARCHAR(24) NOT NULL,
  timeElapsed MEDIUMINT UNSIGNED NOT NULL,
  clicks SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS result_legendary (
  id BINARY(16) PRIMARY KEY,
  userId VARCHAR(24) NOT NULL,
  timeElapsed MEDIUMINT UNSIGNED NOT NULL,
  clicks SMALLINT UNSIGNED NOT NULL
);